[package]
name = "rust-axum-sv"
version = "0.1.0"
edition = "2021"

[dependencies]
axum = "0.6.18"
shuttle-axum = "0.21.0"
shuttle-runtime = "0.21.0"
tokio = "1.28.2"
serde = { version = "1", features = ["derive"] }
serde_json = "1.0"
tower-http = { version = "0.4", features = ["fs"] }